name: ecommerce_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.3.4

dependencies:
  cached_network_image:
  carousel_slider_plus:
  flutter:
    sdk: flutter
  flutter_screenutil:
  flutter_slidable:
  auto_size_text:
  colornames:
  flutter_svg:
  flutter_native_splash:
  readmore:
  smooth_page_indicator:
  retrofit: ^4.9.2
  connectivity_plus: ^7.0.0
  flutter_bloc: ^9.1.1
  dio: ^5.9.2
  get_it: ^9.2.1
  injectable: ^2.7.1+4
  logger: ^2.7.0
  pretty_dio_logger: ^1.4.0
  fluttertoast: ^9.0.0
  shared_preferences: ^2.5.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  build_runner: ^2.13.1
  injectable_generator: ^2.12.1
  json_serializable: ^6.13.1
  retrofit_generator: ^10.2.3


flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/svg_images/



  fonts:
     - family: Poppins
       fonts:
         - asset: assets/fonts/Poppins-.ttf



